version: '3.6'

services:
  # api:
  #   image: nhl-api
  #   build: ./api
  #   volumes:
  #     - ./api:/usr/src/app
  #   networks:
  #     - frontend
  #     - backend
  #   env_file:
  #     - ./api/.env
  #   command: [ "tail", "-f", "/dev/null" ]
  db:
    image: nhl-db
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    image: nhl-app
    build:
      context: ./app
      target: nhl-app
      args:
        TIMEZONE: America/Los_Angeles
    networks:
      - frontend
      - backend
  nginx:
    image: nhl-nginx
    build: ./nginx
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
    internal: true

volumes:
  mysql-data: