version: '3.6'

services:
  # api:
  #   image: nhl-api
  #   build: ./api
  #   volumes:
  #     - ./api:/usr/src/app
  #   networks:
  #     - frontend
  #     - backend
  #   env_file:
  #     - ./api/.env
  #   command: [ "tail", "-f", "/dev/null" ]
  # db:
  #   image: nhl-db
  #   build: ./mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   networks:
  #     - backend
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   env_file:
  #     - ./mysql/.env
  app:
    build:
      target: nhl-app-dev
      args:
        TIMEZONE: America/Los_Angeles
    volumes:
      - ./app:/app
  nginx:
    volumes:
      - ./app/public:/app/public
    ports:
      - 8080:80

# volumes:
#   mysql-data: